### ISSUE TITLE
如何测试你的安卓微信支付客户端

### ISSUE THREAD

**Issue by 0xhhhhh** [xiyuan-fengyu/PayClientDemo#2]
后端一枚，so..

**Comment by xiyuan-fengyu** [comment]
如果有认识的android开发，可以让他帮你打一个包，打包前需要把  
app/src/main/java/com/chetuan/findcar/http/UrlList.java  
中的serverRoot 改为你自己的测试服务器地址  
如果要测试异步回调，可以使用 ngrok 做方向代理

**Comment by 0xhhhhh** [comment]
我正在安装Android Studio，里面的API配置和参数已经改了，就是不知道如何使用POST，等IDE安装好之后我再看下
